import type { Metadata } from "next";
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= "antialiased bg-gray-800 text-white"
      >
        <CopilotKit
          runtimeUrl="/api/copilot"
          // publicApiKey=""
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
