from app.utils.prompts import *
from app.utils.organiser_prompts import *

__all__ = [
    CONTENT_CREATION_SYSTEM_PROMPT,
    GOVERNMENT_PERMISSION_SYSTEM_PROMPT,
    RESOURCE_AGENT_SYSTEM_PROMPT,
    REMAINDER_AGENT_SYSTEM_PROMPT,
    VOLUNTEER_GUIDELINES,
    FEEDBACK_AGENT_SYSTEM_PROMPT,
    ORGANISER_REASONER_SYSTEM_PROMPT,
    ORGANISER_BOT_SYSTEM_PROMPT,
    PROMPT_GENERATOR_SYSTEM_PROMPT,
    INFO_GATHERER_SYSTEM_PROMPT
]